app:
  localization-properties:
    select-language-greeting: 'Выберите ваш язык/Select Your language.'
    select-one-option-of: 'Введите один из вариантов:/Type one of:'
    available-languages:
      - ру
      - ru
      - en
    exit-commands:    # see ru.otus.studentstesting.shell.Exit
      - выйти
      - exit
      - "-"
    questions-resource-urls:
      ru: /questions-ru.csv
      en: /questions-en.csv
spring:
  profiles:
    active: shell
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    console:
  file:
    path: log/student-testing.log
  level:
    org.springframework: debug
---
spring:
  profiles: console
  shell.interactive.enabled: false

---
spring:
  profiles: shell
  shell:
    interactive.enabled: true
    command:
      history.enabled: false
      script.enabled: false
      stacktrace.enabled: false

---
spring:
  profiles: test
  shell.interactive.enabled: false
  main.banner-mode: off
