spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:book-library
    # tcp connection jdbc:h2:tcp://localhost:7072/mem:book-library
    # web connection http://localhost:8082
    username: sa
    password:
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  data:
    mongodb:
#      port: 0
      port: 54812
      database: booklibrary

debug: true
